### ISSUE TITLE
[FIXED/EXPLAINED] well ,it's not working 

### ISSUE THREAD

**Issue by abderrahmanebenhalima** [Sherly1001/tame#1]
i just tried it
and it still showing the"seen" to the ones who sent me messages unfortunately,even though i checked the block seend the the block typing.
i set it up as this screenshot of yours 
[Screenshot](https://addons.mozilla.org/user-media/previews/full/283/283872.png?modified=1686915582)
(i gave you a feedback in the mozilla add-ons store but i can't reply back so i'll follow with you here )

**Comment by Sherly1001** [comment]
@abderrahmanebenhalima plz note that there are two blocking mode, since you are working on `blacklist` mode, it only block "seen" for conversations which you added (default there is no conversation).
If you want to block all conversations, just switch to `whitelist` mode.

**Comment by abderrahmanebenhalima** [comment]
> @abderrahmanebenhalima plz note that there are two blocking mode, since you are working on `blacklist` mode, it only block "seen" for conversations which you added (default there is no conversation). If you want to block all conversations, just switch to `whitelist` mode.



> @abderrahmanebenhalima plz note that there are two blocking mode, since you are working on `blacklist` mode, it only block "seen" for conversations which you added (default there is no conversation). If you want to block all conversations, just switch to `whitelist` mode.

okay i'll try this and i'll tell you 
thanks for the information

**Comment by abderrahmanebenhalima** [comment]
> @abderrahmanebenhalima plz note that there are two blocking mode, since you are working on `blacklist` mode, it only block "seen" for conversations which you added (default there is no conversation). If you want to block all conversations, just switch to `whitelist` mode.

well 
that's really working !
thank you so much 
And please simplify the explanation of the whitelist and the blacklist concept. 
(i'll switch to 5 stars in the mozilla store and i'll keep supporting this extension because it's the reason that i'll start using firefox again )
So thank you so much for the useful extension
and i hope it'll extends to the instagram too in the future.
have a great day/night

**Comment by Sherly1001** [comment]
Great to hear that.
> because it's the reason that i'll start using firefox again

For chromium, i have deployed it to Chrome Web Store too, you can checkout it [here]( https://chrome.google.com/webstore/detail/tame/ekkfmgebnjoeklkbnnmkgclphcgemnml).

**Comment by abderrahmanebenhalima** [comment]
> Great to hear that.
> 
> > because it's the reason that i'll start using firefox again
> 
> For chromium, i have deployed it to Chrome Web Store too, you can checkout it [here](https://chrome.google.com/webstore/detail/tame/ekkfmgebnjoeklkbnnmkgclphcgemnml).

thank you so much for all your hard-work
it's a pretty amazing privacy extension !
