### ISSUE TITLE
[Issue] Extension is removed from firefox addons site

### ISSUE THREAD

**Issue by zephyros-dev** [Sherly1001/tame#2]
I managed to install the extension a few week ago on Firefox using the link in the README. However it is gone from the site as of now.
Thank you for the wonderful extension.

**Comment by Sherly1001** [comment]
It seems that it was disabled by the admins. I have just emailed them to ask for the reason. Thank you for submitting the issue.

**Comment by Sherly1001** [comment]
Hi @zephyros-dev,
Since the admin team has not responded yet, I have submitted this extension with the name **tame v2**. You can check it [here](https://addons.mozilla.org/en-US/firefox/addon/tamev2/).
