### ISSUE TITLE
Blocking seen and typing features in end-to-end chats are not working

### ISSUE THREAD

**Issue by flame-0** [Sherly1001/tame#3]
With the recent update from Meta, the 'seen' and 'typing' blocking features are not functioning in end-to-end chats; however, chats without end-to-end encryption still work.

**Comment by Sherly1001** [comment]
@flame-0 I have checked, and it works pretty well. Could you provide some evidence, video, or steps to reproduce this bug?

**Comment by flame-0** [comment]
> @flame-0 I have checked, and it works pretty well. Could you provide some evidence, video, or steps to reproduce this bug?

For privacy reasons, I sent how to reproduce the issue in our DMs in Discord.

**Comment by vomenh1804** [comment]
Facebook's codes are suck and their 'end to end' chats are different base on the time they got transferred. I've encountered this problem myself but not with all 'end to end' chats ~~

**Comment by Sherly1001** [comment]
Upgraded in the latest version. Check it out [here](https://addons.mozilla.org/en-US/firefox/addon/tamev2/).
