### ISSUE TITLE
Sending chat/messages not working.

### ISSUE THREAD

**Issue by kenarsene** [Sherly1001/tame#5]
Chat messages aren't sending when the extension is active.

**Comment by VoMenh18** [comment]
+1, this happened to me too

**Comment by Sherly1001** [comment]
Thank you for letting me know. It seems there have been some changes in the latest Facebook update. It might take some time, but I will fix it as soon as possible.

**Comment by Sherly1001** [comment]
Fixed in the newest version (1.2).
For Chromium users, it may take a little time for the new version to be published on the web store.
