### ISSUE TITLE
Can't turn on the extension in private mode

### ISSUE THREAD

**Issue by VoMenh18** [Sherly1001/tame#6]
![image](https://github.com/user-attachments/assets/16ed026d-8fee-43c9-99a4-d8c066f1aabb)
Is this normal?

**Comment by Sherly1001** [comment]
@VoMenh18 This is completely normal. If you want it to run in incognito mode, you need to remove[ this line](https://github.com/Sherly1001/tame/blob/main/manifest.json#L10) in the manifest.json file.
Adding such a configuration will help the extension get approved faster when publishing to the web store.

**Comment by Sherly1001** [comment]
@VoMenh18 It can now be used in private mode.
